set_property IOSTANDARD LVCMOS33 [get_ports ds_0]
set_property IOSTANDARD LVCMOS33 [get_ports sh_cp_0]
set_property IOSTANDARD LVCMOS33 [get_ports st_cp_0]
set_property PACKAGE_PIN L15 [get_ports ds_0]
set_property PACKAGE_PIN L14 [get_ports st_cp_0]
set_property PACKAGE_PIN M15 [get_ports sh_cp_0]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN K13 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN L13 [get_ports {GPIO_0_0_tri_io[0]}]

set_property PACKAGE_PIN K13 [get_ports {GPIO_0_tri_o[0]}]
set_property PACKAGE_PIN L13 [get_ports {GPIO_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[0]}]

set_property PACKAGE_PIN L13 [get_ports {UP_BUTTON_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {UP_BUTTON_tri_i[0]}]
set_property PACKAGE_PIN K13 [get_ports {DOWN_BUTTON_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DOWN_BUTTON_tri_i[0]}]
