set_property IOSTANDARD LVCMOS33 [get_ports ds_0]
set_property IOSTANDARD LVCMOS33 [get_ports sh_cp_0]
set_property IOSTANDARD LVCMOS33 [get_ports st_cp_0]
set_property PACKAGE_PIN M15 [get_ports ds_0]
set_property PACKAGE_PIN L15 [get_ports sh_cp_0]
set_property PACKAGE_PIN L14 [get_ports st_cp_0]
